<?php
require_once __DIR__.'/auth.php'; require_once __DIR__.'/layout.php'; require_once __DIR__.'/image_helper.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){try{
 $action=$_POST['action']??'';
 if($action==='save'){$id=(int)($_POST['id']??0);$oldImage=trim($_POST['existing_image']??'');$image=trim($_POST['image_url']??'');$uploaded=uploadImage('image_file');if($uploaded)$image=$uploaded;if(!$image)throw new RuntimeException('Please provide an image URL or choose an image file.');$data=[trim($_POST['title']??''),trim($_POST['description']??''),$image,trim($_POST['category']??''),$_POST['status']??'published'];if($id){$s=$pdo->prepare("UPDATE gallery SET title=?,description=?,image_url=?,category=?,status=? WHERE id=?");$s->execute([...$data,$id]);if($uploaded&&$oldImage&&$oldImage!==$image)deleteLocalImage($oldImage);flash('Gallery item updated.');}else{$s=$pdo->prepare("INSERT INTO gallery(title,description,image_url,category,status) VALUES(?,?,?,?,?)");$s->execute($data);flash('Gallery image added.');}}
 elseif($action==='delete'){$id=(int)$_POST['id'];$s=$pdo->prepare("SELECT image_url FROM gallery WHERE id=?");$s->execute([$id]);$old=$s->fetchColumn();$s=$pdo->prepare("DELETE FROM gallery WHERE id=?");$s->execute([$id]);deleteLocalImage($old);flash('Gallery item deleted.');}
}catch(Throwable $e){flash($e->getMessage(),'error');}redirect('gallery_management.php');}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare("SELECT * FROM gallery WHERE id=?");$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$rows=$pdo->query("SELECT * FROM gallery ORDER BY id DESC")->fetchAll();pageStart('Gallery Management','gallery');
?>
<div class="flex justify-between items-center mb-6"><div><h2 class="text-2xl font-bold">Gallery</h2><p class="text-sm text-slate-500 mt-1">Manage activity and organization images.</p></div><button onclick="openModal('galleryModal')" class="rounded-xl bg-emerald-700 px-5 py-3 text-white font-semibold">+ Add Image</button></div>
<div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><?php foreach($rows as $r):?><div class="bg-white border rounded-2xl overflow-hidden shadow-sm"><img src="<?=h($r['image_url'])?>" class="w-full h-48 object-cover"><div class="p-4"><div class="font-semibold"><?=h($r['title']?:'Untitled')?></div><div class="text-xs text-slate-400 mt-1"><?=h($r['category'])?></div><div class="mt-4 flex justify-between"><a href="?edit=<?=$r['id']?>" class="text-emerald-700">Edit</a><form method="POST" onsubmit="return confirm('Delete this image?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="text-red-600">Delete</button></form></div></div></div><?php endforeach;?></div>
<?php $m=$edit?:['id'=>'','title'=>'','description'=>'','image_url'=>'','category'=>'','status'=>'published'];modalStart('galleryModal',$edit?'Edit Gallery Item':'Add Gallery Image');?>
<form method="POST" enctype="multipart/form-data" class="space-y-4"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=h($m['id'])?>"><input type="hidden" name="existing_image" value="<?=h($m['image_url'])?>">
<?php inputField('title','Image Title',$m['title']);?><?php inputField('category','Category',$m['category'],'text',false,'Activities, Care, Events...');?><?php textareaField('description','Description',$m['description'],3);?>
<div><label class="mb-1 block text-sm font-medium">Image File</label><input type="file" name="image_file" accept="image/jpeg,image/png,image/webp,image/gif" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 bg-white"><p class="text-xs text-slate-400 mt-1">JPG, PNG, WEBP or GIF · max 8 MB.</p></div>
<?php inputField('image_url','Or Image URL',$m['image_url'],'url',false,'https://example.com/image.jpg'); ?><?php if($m['image_url']): ?><div class="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><img src="<?=h($m['image_url'])?>" class="h-16 w-24 rounded-lg object-cover"><span class="text-xs text-slate-500">Current image</span></div><?php endif; ?>
<div><label class="text-sm font-medium">Status</label><select name="status" class="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="published" <?=$m['status']==='published'?'selected':''?>>Published</option><option value="draft" <?=$m['status']==='draft'?'selected':''?>>Draft</option></select></div>
<div class="flex justify-end gap-3"><button type="button" onclick="closeModal('galleryModal')" class="rounded-xl border px-5 py-2.5">Cancel</button><button class="rounded-xl bg-emerald-700 px-5 py-2.5 text-white font-semibold"><?=$edit?'Update Image':'Save Image'?></button></div></form>
<?php modalEnd();if(isset($_GET['edit'])&&$edit):?><script>document.addEventListener('DOMContentLoaded',function(){openModal('galleryModal');});</script><?php endif;pageEnd();?>
