<?php
require_once __DIR__.'/auth.php'; require_once __DIR__.'/layout.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){try{
 if($_POST['action']==='save'){$id=(int)($_POST['id']??0);$data=[trim($_POST['title']),$_POST['tour_date'],$_POST['tour_time']?:null,trim($_POST['location']),trim($_POST['description']),trim($_POST['instructions']),$_POST['status']];
  if($id){$s=$pdo->prepare("UPDATE tours SET title=?,tour_date=?,tour_time=?,location=?,description=?,instructions=?,status=? WHERE id=?");$s->execute([...$data,$id]);flash('Tour schedule updated.');}
  else{$s=$pdo->prepare("INSERT INTO tours(title,tour_date,tour_time,location,description,instructions,status) VALUES(?,?,?,?,?,?,?)");$s->execute($data);flash('Tour schedule added.');}
 }else{$s=$pdo->prepare("DELETE FROM tours WHERE id=?");$s->execute([(int)$_POST['id']]);flash('Tour deleted.');}
}catch(Exception $e){flash($e->getMessage(),'error');}redirect('schedule_management.php');}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare("SELECT * FROM tours WHERE id=?");$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$rows=$pdo->query("SELECT * FROM tours ORDER BY tour_date ASC,tour_time ASC")->fetchAll();pageStart('Tour Schedule Management','schedule');
?>
<div class="flex justify-between items-center mb-6"><div><h2 class="text-2xl font-bold">Upcoming Tours & Schedules</h2><p class="text-sm text-slate-500 mt-1">Manage dates, times, locations and instructions.</p></div><button onclick="openModal('tourModal')" class="rounded-xl bg-emerald-700 px-5 py-3 text-white font-semibold">+ Add Schedule</button></div>
<div class="bg-white border rounded-2xl shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">Tour</th><th class="p-4 text-left">Date</th><th class="p-4 text-left">Time</th><th class="p-4 text-left">Location</th><th class="p-4 text-left">Status</th><th class="p-4 text-right">Actions</th></tr></thead><tbody>
<?php foreach($rows as $r):?><tr class="border-t"><td class="p-4 font-semibold"><?=h($r['title'])?></td><td class="p-4"><?=date('M d, Y',strtotime($r['tour_date']))?></td><td class="p-4"><?=$r['tour_time']?date('H:i',strtotime($r['tour_time'])):'-'?></td><td class="p-4"><?=h($r['location'])?></td><td class="p-4"><?=h($r['status'])?></td><td class="p-4"><div class="flex justify-end gap-3"><a href="?edit=<?=$r['id']?>" class="text-emerald-700">Edit</a><form method="POST" onsubmit="return confirm('Delete this schedule?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="text-red-600">Delete</button></form></div></td></tr><?php endforeach;?>
</tbody></table></div></div>
<?php $m=$edit?:['id'=>'','title'=>'','tour_date'=>'','tour_time'=>'','location'=>'','description'=>'','instructions'=>'','status'=>'upcoming'];modalStart('tourModal',$edit?'Edit Tour Schedule':'Add Tour Schedule');?>
<form method="POST" class="space-y-4"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=h($m['id'])?>">
<?php inputField('title','Tour Title',$m['title'],'text',true);?><div class="grid sm:grid-cols-2 gap-4"><?php inputField('tour_date','Date',$m['tour_date'],'date',true);?><?php inputField('tour_time','Time',$m['tour_time'],'time');?></div><?php inputField('location','Location',$m['location']);?><?php textareaField('description','Description',$m['description'],3);?><?php textareaField('instructions','Information / Instructions',$m['instructions'],3);?>
<div><label class="text-sm font-medium">Status</label><select name="status" class="mt-1 w-full rounded-xl border px-3 py-2.5"><option value="upcoming" <?=$m['status']==='upcoming'?'selected':''?>>Upcoming</option><option value="completed" <?=$m['status']==='completed'?'selected':''?>>Completed</option><option value="cancelled" <?=$m['status']==='cancelled'?'selected':''?>>Cancelled</option></select></div>
<div class="flex justify-end gap-3"><button type="button" onclick="closeModal('tourModal')" class="rounded-xl border px-5 py-2.5">Cancel</button><button class="rounded-xl bg-emerald-700 px-5 py-2.5 text-white font-semibold"><?=$edit?'Update Schedule':'Save Schedule'?></button></div></form>
<?php modalEnd();if(isset($_GET['edit'])):?><script>openModal('tourModal');</script><?php endif;pageEnd();?>
